"""add_intelligence_module_statuses

Revision ID: afe6139c5330
Revises: 1c6fa2941993
Create Date: 2026-07-04 16:47:55.143246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_intelligence_module_statuses

Revision ID: afe6139c5330
Revises: 1c6fa2941993
Create Date: 2026-07-04 16:47:55.143246

"""



# revision identifiers, used by Alembic.
revision: str = 'afe6139c5330'
down_revision: Union[str, Sequence[str], None] = '1c6fa2941993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if table already exists in connection defensively
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if '_alembic_tmp_repository_analyses' in tables:
        op.drop_table('_alembic_tmp_repository_analyses')
    
    if 'intelligence_module_statuses' not in tables:
        op.create_table('intelligence_module_statuses',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('analysis_id', sa.String(length=36), nullable=False),
            sa.Column('module_name', sa.String(length=100), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('started_at', sa.DateTime(), nullable=True),
            sa.Column('finished_at', sa.DateTime(), nullable=True),
            sa.Column('duration_seconds', sa.Float(), nullable=True),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('cache_hit', sa.Boolean(), nullable=True),
            sa.Column('files_processed', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['analysis_id'], ['repository_analyses.analysis_id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('analysis_id', 'module_name', name='uq_analysis_module')
        )
        with op.batch_alter_table('intelligence_module_statuses', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_intelligence_module_statuses_analysis_id'), ['analysis_id'], unique=False)

    with op.batch_alter_table('repository_analyses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('current_stage',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('current_module',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_repository_analyses_commit_sha'))
        batch_op.create_index(batch_op.f('ix_repository_analyses_commit_sha'), ['commit_sha'], unique=True)

    with op.batch_alter_table('repository_snapshots', schema=None) as batch_op:
        batch_op.alter_column('previous_snapshot_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_repository_snapshots_previous_snapshot', 'repository_snapshots', ['previous_snapshot_id'], ['snapshot_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('previous_snapshot_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('repository_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_analyses_commit_sha'))
        batch_op.create_index(batch_op.f('ix_repository_analyses_commit_sha'), ['commit_sha'], unique=False)
        batch_op.alter_column('current_module',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('current_stage',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('intelligence_module_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_module_statuses_analysis_id'))
    op.drop_table('intelligence_module_statuses')

    op.create_table('_alembic_tmp_repository_analyses',
    sa.Column('analysis_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('repository_snapshot_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('commit_sha', sa.VARCHAR(length=40), nullable=False),
    sa.Column('analysis_version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('engine_version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('current_stage', sa.VARCHAR(length=100), nullable=True),
    sa.Column('progress', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('completed_stages', sa.TEXT(), nullable=True),
    sa.Column('files_processed', sa.INTEGER(), nullable=True),
    sa.Column('current_module', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['repository_snapshot_id'], ['repository_snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    # ### end Alembic commands ###
